  - name: Add gpg for Skype
    apt_key:
      url: https://repo.skype.com/data/SKYPE-GPG-KEY
      state: present
  
  - apt_repository:
      repo: deb [arch=amd64] https://repo.skype.com/deb stable main
      state: present
      filename: skype
      update_cache: yes

  - name: Installing Skype
    apt:
      name: skypeforlinux
