  - name: Test Slack installation
    shell: "dpkg -s slack-desktop 2>/dev/null >/dev/null"
    register: installed

  - name: Downloading Slack
    get_url:
      url: https://downloads.slack-edge.com/linux_releases/{{ slackPackageDeb }}
      dest: /tmp
      mode: 0644

  - name: Installing Slack
    apt:
      deb: /tmp/{{ slackPackageDeb }}

  - name: Removing {{ slackPackageDeb }} package
    file:
      state: absent
      path: /tmp/{{ slackPackageDeb }}
