  - name: Add gpg for Google Chrome
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present
  
  - apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: google-chrome
      update_cache: yes

  - name: Installing Google Chrome
    apt:
      name: google-chrome-stable
