  - name: Install base packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - gcc
      - make
      - vim
      - htop
      - gnome-tweak-tool
      - virtualbox-dkms
    tags:
      - packages
