# https://github.com/geerlingguy/ansible-role-jenkins
jenkins_package_state: latest
jenkins_admin_username: admin
jenkins_admin_password: admin123
jenkins_plugins: [
  'sonar',
  'nexus-artifact-uploader',
  'ansible',
  'workflow-aggregator',
  'slack',
  'slack-uploader',
  'git',
  'github',
  'credentials-binding',
  'pipeline-utility-steps',
  'disk-usage',
  'ws-cleanup'
  ]
maven_major: 3
maven_release: 3.5.3
maven_version: 3.5.3
java_packages:
  - openjdk-8-jdk
