  - name: Copying bash files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'bash/.bashrc',       dest: '/home/{{ username }}/.bashrc',         mode: 0644 }
      - { src: 'bash/.bash_aliases', dest: '/home/{{ username }}/.bash_aliases', mode: 0644 }
