  - name: Copying git files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: rafael
      group: rafael
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'git/.gitconfig',   dest: '/home/rafael/.gitconfig',    mode: 0644 }
      - { src: 'git/.gitexcludes', dest: '/home/rafael/.gitexcludes', mode: 0644 }
