  - name: Copying git files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'git/.gitconfig',   dest: '/home/{{ username }}/.gitconfig',    mode: 0644 }
      - { src: 'git/.gitexcludes', dest: '/home/{{ username }}/.gitexcludes', mode: 0644 }
