  - name: Gather OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release}}.yml"
      - "{{ ansible_distribution|lower }}.yml"
    tags: vars

    #- name: Environment setup
    #import_tasks: environment.yml

  - name: Files for bash
    import_tasks: bash.yml

  - name: Files for git
    import_tasks: git.yml

  - name: Virtualbox environment
    import_tasks: virtualbox.yml

  - name: SSH environment
    import_tasks: ssh.yml

  - name: Ubuntu Bionic
    import_tasks: ubuntu-bionic/main.yml
    when: (ansible_distribution|lower == "ubuntu" and ansible_distribution_release == "bionic")

  - name: Ubuntu Disco
    import_tasks: ubuntu-disco/main.yml
    when: (ansible_distribution|lower == "ubuntu" and ansible_distribution_release == "disco")
