- name: Check that the somefile.conf exists
  stat:
    path: /usr/local/bin/idea-IC-182.5107.16
  register: stat_result

- name: Downloading IntelliJ
  unarchive:
    src: https://download-cf.jetbrains.com/idea/ideaIC-{{ ideaVersion }}.tar.gz
    dest: /usr/local/bin
    remote_src: ye
  when: stat_result.stat.exists == False 
