  - name: Docker install pre required packages
    apt:
      state: present
      name: "{{ item }}"
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add gpg for Docker Community Edition
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      filename: docker
      update_cache: yes

  - name: Installing Docker Community Edition
    apt:
      name: docker-ce
