  - name: Copying bash files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: rafael
      group: rafael
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'bash/.bashrc',       dest: '/home/rafael/.bashrc',         mode: 0644 }
      - { src: 'bash/.bash_aliases', dest: '/home/rafael/.bash_aliases', mode: 0644 }
